### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by Cash2m** [TYPO3/CmsComposerInstallers#10]
Hi there,

we are using composer more and more in our TYPO3 development/deployment process. There are some open pull requests in this repository that haven't been merged for a long time.  
Is this this project dead? Do you need help? I'm asking since this is a dependency of the TYPO3.CMS project and a very essential addition to the T3 environment.

Thanks for your work so far - keep it up!

**Comment by t3dev** [comment]
I don't think the project is dead. It's just working, I tend to think that's a good sign. ;)

**Comment by tmaroschik** [comment]
Hey, everything here is fine. We're just working on another version of this installer hopefully for the 7 LTS, so it doesn't make so much sense to invest here too much ;)
