### ISSUE TITLE
Replace PHP version constraints in entry point scripts

### ISSUE THREAD

**Issue by gilbertsoft** [TYPO3/CmsComposerInstallers#111]
The change https://review.typo3.org/c/Packages/TYPO3.CMS/+/67365 introduces also an upper check for the PHP version. Imho it could make sense if we replace the PHP versions during the entry point setup here in https://github.com/TYPO3/CmsComposerInstallers/blob/master/src/Plugin/Core/InstallerScripts/EntryPoint.php.

**Comment by helhum** [comment]
The code here only changes the require line and leaves the rest of the file as is. Therefore no change is required here.

**Comment by helhum** [comment]
oh, if you mean replacing the version check dynamically with the Composer constraints, then I'd disagree to change anything here as well and rather rely on the functionality Composer introduced.

**Comment by gilbertsoft** [comment]
> rather rely on the functionality Composer introduced

And what's that? Did you see the discussion at Slack, linked from the core patch above. The idea was to get a clear error in the entry scripts by checking the version constraints. And for a Composer install it would imho make sense to use the Composer constraints therefor.

**Comment by helhum** [comment]
> The idea was to get a clear error in the entry scripts by checking the version constraints. And for a Composer install it would imho make sense to use the Composer constraints therefor.

That is **precisely** Composer 2.0 runtime functionality. Check TYPO3 Console 6.0 to see it in action.

Implementing that for TYPO3 is a matter of a single requirement change (making Composer 2.0 mandatory) and removal of our own checks.

**Comment by helhum** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/67371
