### ISSUE TITLE
TYPO3 8 ELTS Installation fails with CMSComposerInstallers 1.5.9

### ISSUE THREAD

**Issue by pixelbrackets** [TYPO3/CmsComposerInstallers#115]
*What did I do?*

- Update TYPO3 ELTS to version 8.7.40, which updates the CMSComposerInstallers from 1.5.6 to 1.5.9
- Deploy to build systems which clear the "vendor" directory and then run `composer install --no-dev` using the newly updated `composer.lock`

*What did I expect*

- Composer installs all packages and all TYPO3 extensions trough the installer

*What happened instead?*

- Composer install all packages, the installation of extension fails

```bash
PHP Fatal error:  Uncaught Error: Class 'TYPO3\CMS\Composer\Util\T3xDownloaderUtility' not found in /home/xxxxxx/vendor/typo3/cms-composer-installers/src/Installer/Downloader/T3xDownloader.php:51
```

**Comment by helhum** [comment]
@benjaminkott can you have a look into this? Thanks

**Comment by pixelbrackets** [comment]
Found the issue → T3xDownloaderUtility uses the wrong namespace. This will work out in newer installations, but not with the path resolver. I'll send a PR asap.

**Comment by pixelbrackets** [comment]
Confirmed that this is the issue and the PR works. I used my patch repository to overwrite the installer and installation builds now run without errors.

**Comment by pixelbrackets** [comment]
@helhum Could you please tag a release 1.5.10 for the [1.5.x branch](https://github.com/TYPO3/CmsComposerInstallers/compare/v1.5.9...1.5.x)? ☺️

**Comment by helhum** [comment]
@pixelbrackets done
