### ISSUE TITLE
T3xDownloader2 incompatible with Composer\Downloader\ArchiveDownloader >= 2.3.0

### ISSUE THREAD

**Issue by knusperpixel** [TYPO3/CmsComposerInstallers#132]
typo3/cms-composer-installers:1.5.10

Declaration of TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader2::extract(Composer\Package\PackageInterface $package, $file, $path) must be compatible with Composer\Downloader\ArchiveDownloader::extract(Composer\Package\PackageInterface $package, string $file, string $path): React\Promise\PromiseInterface

**Comment by helhum** [comment]
Thanks for reaching out. Next time, please take some minutes to at least describe your issue as full sentence.

typo3/cms-composer-installers:1.5.10 is not supported any more. If you are using TYPO3 ELTS versions, please also use Composer 2.2 LTS versions to manage these, or reach out to TYPO3 ELTS support, whether they can provide a version of composer installers that works with latest Composer versions and outdated TYPO3 versions.
