### ISSUE TITLE
Documentation is treated as extension

### ISSUE THREAD

**Issue by linawolf** [TYPO3/CmsComposerInstallers#139]
All Official TYPO3 manuals have the type 

```
    "type": "typo3-cms-documentation",
```

After the update to `typo3/cms-composer-installers` v5.0 manuals are however treated like extensions which they are not. Therefore 
there is an error thrown in ExtensionKeyResolver:

```
Extension with package name "typo3/reference-coreapi" does not define an extension key.
```

**Comment by helhum** [comment]
Thanks. Hm, I have multiple questions:

* What is the use case to install those packages alongside TYPO3?
* In which folders were they installed then before? 
* What was/ is the expectation they should be installed?
* Didn't you get deprecation messages before, that those packages need an extension key?

**Comment by linawolf** [comment]
We do install typo3 into the manuals so we can use CLI commands to create the codesnippets or screenshots.

This worked well until the update to v5 of the composer installer. No warnings displayed.

Have a look here: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/main/composer.json

**Comment by linawolf** [comment]
The type "typo3-cms-documentation" is required to have the documentation render.

**Comment by ohader** [comment]
> The type "typo3-cms-documentation" is required to have the documentation render.

Why is that? Where is that required? I could not find any type `typo3-cms-documentation` on packagist.org (https://packagist.org/?type=typo3-cms-documentation)

**Comment by linawolf** [comment]
It is required in the rendering pipeline as far as I understand, Maybe @marble can enlighten us here? No the documentation is not on packagist (yet)

**Comment by linawolf** [comment]
Can be solved by just defining an extension key... Seems like I didnt see the solution right before my eyes. There is no harm in defining one...
