### ISSUE TITLE
The installer should adhere env TYPO3_PATH_ROOT

### ISSUE THREAD

**Issue by liayn** [TYPO3/CmsComposerInstallers#145]
The whole Core uses the env `TYPO3_PATH_ROOT` to calculate paths within document root.
Unfortunately, the installer here does not.

The consequence is that it is possible to have a classic installation, where the document root is defined via `TYPO3_PATH_ROOT`, whereas in a composer installation this is dictated by the `web-dir` option.

For scenarios where the `web-dir` option is not feasible (e.g. different doc roots on different stages, like dev, stage, prod), this is not usable.

It would be much better to allow to override the `web-dir`  option with `TYPO3_PATH_ROOT`, so it all works out as intended.

_Side note: https://github.com/TYPO3/CmsComposerInstallers/blob/main/res/php/autoload-include.tmpl.php still creates the `TYPO3_PATH_WEB` which seems to be unused for a very long time._

**Comment by liayn** [comment]
Example:

Live instance is behind a corporate F5 reverse proxy and runs the instance in a subdirectory of the main website

staging: https://project.example.com/
live: https://www.example.com/division/subcompany/ (reverse proxy on the TLD)

folder structure:

```
staging:
 - public/_assets/...
``` 

``` 
live:
 - public/division/subcompany/_assets
```

**Comment by liayn** [comment]
Target version: composer installers v4 and v5 (Core v11 + v12)

**Comment by helhum** [comment]
> Target version: composer installers v4 and v5 (Core v11 + v12)

With these versions, `root-dir` (aka `TYPO3_PATH_ROOT`) and `web-dir` (aka `TYPO3_PATH_WEB`) are set to the same path by the plugin. In the long run (TYPO3 13) this can and should be broken down to one path only. 
So my questions is: How do you achieve to set these to different values with using the configuration in composer.json?

**Comment by liayn** [comment]
> `TYPO3_PATH_WEB` 

Is not used by Core since a long time. (found not traces)

> web-dir and root-dir

are kept the same by the Config class.

> web-dir

is only used within the composer plugin context and nowhere else

> root-dir

is the same as web-dir and is populated to `TYPO3_PATH_ROOT`, which is actually used by Core.

**Comment by liayn** [comment]
> So my questions is: How do you achieve to set these to different values with using the configuration in composer.json?

Sorry, I misunderstood your question:
They should still be the same. I'm not trying to get them "apart".

I only try to set the `web-dir` option (aka doc root) by ENV var. The matching var is `TYPO3_PATH_ROOT`, which Core uses for all the things.

**Comment by liayn** [comment]
Additional info:

Core's `PackageArtifactBuilder`  relies on `web-dir` from composer, in order to create the `_assets` symlinks.
Hence, it does not care about the `TYPO3_PATH_ROOT` env.

My patch suggestion changes exactly that. It makes `TYPO3_PATH_ROOT` (aka doc-root) the value for `web-dir` (aka doc-root).

**Comment by helhum** [comment]
Let's try to consolidate discussions again. I'm closing this one here in favor of discussing it further at #146
