### ISSUE TITLE
Could you explain a little what this does?

### ISSUE THREAD

**Issue by LionsAd** [TYPO3/CmsComposerInstallers#18]
Hi,

Coming over from Drupal, we are currently working in integrating composer more with the core system. The current integration we have is rather ... lacking.

It seems typo3 has a pretty nice idea on how to integrate it with 'legacy' modules and it seems this project is key to that.

Would it be possible to explain a little the strategy that is used here and what is overwritten how from the core composer library?

Maybe we can collaborate somewhat as it seems we try to solve the same problem (support legacy extensions / modules / libraries in a composer enabled world.)

Thanks,

Fabian

**Comment by helhum** [comment]
Hey @LionsAd !

Thanks for your interest in our composer strategy! I gladly explain our current status and where we're currently heading to you. The easiest way would be if you would join our slack: https://forger.typo3.org/slack

If you contact me there, I will be notified. My username there @helhum as well

**Comment by helhum** [comment]
@LionsAd https://wiki.typo3.org/Composer

Feel free to contact me on Slack if you have further questions!
