### ISSUE TITLE
Add app on root package

### ISSUE THREAD

**Issue by pniederlag** [TYPO3/CmsComposerInstallers#37]
Is the use case of adding an app (Classes, Configuration, Resources, ...) in the root package a supported use case?

In practice we often have one "main" extension per project (in classic mode in would reside in typo3conf/ext/xxyyy and everything is stitched together via git submodules).

* splitting a project across git submodules has proven to be error prone

Now composer seems to come to the rescue. However as soon as we start to maintain two separate packages for the distribution and for the application itself(By application I refer to a classic typo3 extension) we again get into troubles because we need to update the external dependency all the time.

Do you get my point?

I think I could add Classes on the root-package (and announce them to the Classloader), however I'd also like to make use of the feature to split out the (public) web folder. How could this work out when adding the application on the root-package?

Do you have any suggestion, best practice on the setup of a project or vision/roadmap for improvements?

Thx for any feedback

**Comment by helhum** [comment]
You have multiple options which are possible right now.

1. Define a web folder (`web`) and put the distribution extension in `web/typo3conf/ext/site_package` and register the class loading information in the root package
1. Put the extension in an arbitrary folder and "register" it for inclusion with a path repository https://getcomposer.org/doc/05-repositories.md#path

Both of these are possible right now already.
