### ISSUE TITLE
Progress output even with --no-progress

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/CmsComposerInstallers#42]
T3X packages are always downloaded with progress, even if `--no-progress` was passed to Composer.

**Comment by helhum** [comment]
Are you willing to create a PR for this? If not, I tend to close it.

**Comment by mbrodala** [comment]
I already looked into this back then but couldn't figure out why exactly this happens. The `T3xDownloader` is registered and used properly AFAIS and the Composer `DownloadManager` should forward whether progress should be outputted or not. Thus ATM I cannot provide a fix.

It's not an urgent issue, just noticed the difference.

**Comment by helhum** [comment]
Ok, thanks. I will close this then
