### ISSUE TITLE
ErrorException "Undefined index: conflicts"

### ISSUE THREAD

**Issue by copitz** [TYPO3/CmsComposerInstallers#44]
Exception stack trace while installing powermail:

    - Installing typo3-ter/powermail (2.25.0)
        Downloading https://typo3.org/extensions/repository/download/powermail/2.25.0/t3x/
        Downloading: 100%
        Writing ~/.composer/cache/files/typo3-ter/powermail/e0bca4beb5a127bf561158ceadb329a6c7225ee8.t3x into cache from typo3conf/ext/powermail/3d5ec0e70bf2293612173fdfe7fdac26
        Extracting archive

      [ErrorException]
      Undefined index: conflicts

    Exception trace:
     () at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:310
     Composer\Util\ErrorHandler::handle() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:310
     TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->fixEmConf() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:251
     TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->constructEmConf() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:236
     TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->writeEmConf() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:77
     TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->extract() at phar:///opt/composer/composer.phar/src/Composer/Downloader/ArchiveDownloader.php:43
     Composer\Downloader\ArchiveDownloader->download() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:50
     TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->download() at phar:///opt/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:213
     Composer\Downloader\DownloadManager->download() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/ExtensionInstaller.php:175
     TYPO3\CMS\Composer\Installer\ExtensionInstaller->installCode() at Packages/Libraries/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/ExtensionInstaller.php:104
     TYPO3\CMS\Composer\Installer\ExtensionInstaller->install() at phar:///opt/composer/composer.phar/src/Composer/Installer/InstallationManager.php:152
     Composer\Installer\InstallationManager->install() at phar:///opt/composer/composer.phar/src/Composer/Installer/InstallationManager.php:139
     Composer\Installer\InstallationManager->execute() at phar:///opt/composer/composer.phar/src/Composer/Installer.php:569
     Composer\Installer->doInstall() at phar:///opt/composer/composer.phar/src/Composer/Installer.php:228
     Composer\Installer->run() at phar:///opt/composer/composer.phar/src/Composer/Command/UpdateCommand.php:173
     Composer\Command\UpdateCommand->execute() at phar:///opt/composer/composer.phar/vendor/symfony/console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at phar:///opt/composer/composer.phar/vendor/symfony/console/Application.php:844
     Symfony\Component\Console\Application->doRunCommand() at phar:///opt/composer/composer.phar/vendor/symfony/console/Application.php:192
     Symfony\Component\Console\Application->doRun() at phar:///opt/composer/composer.phar/src/Composer/Console/Application.php:166
     Composer\Console\Application->doRun() at phar:///opt/composer/composer.phar/vendor/symfony/console/Application.php:123
     Symfony\Component\Console\Application->run() at phar:///opt/composer/composer.phar/src/Composer/Console/Application.php:99
     Composer\Console\Application->run() at phar:///opt/composer/composer.phar/bin/composer:43

**Comment by igodorogea** [comment]
Something similar here with google_services

```
- Installing typo3-ter/google-services (1.0.3)
    Downloading: 100%
    Extracting archive


  [ErrorException]
  Undefined index: 258b3bff


Exception trace:
 () at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:123
 Composer\Util\ErrorHandler::handle() at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:123
 TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->getEmConfMetaData() at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:246
 TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->writeEmConf() at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:70
 TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->extract() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Downloader/ArchiveDownloader.php:43
 Composer\Downloader\ArchiveDownloader->download() at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/Downloader/T3xDownloader.php:50
 TYPO3\CMS\Composer\Installer\Downloader\T3xDownloader->download() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/ExtensionInstaller.php:191
 TYPO3\CMS\Composer\Installer\ExtensionInstaller->installCode() at /var/www/vhosts/localhost/vendor/typo3/cms-composer-installers/Classes/TYPO3/CMS/Composer/Installer/ExtensionInstaller.php:123
 TYPO3\CMS\Composer\Installer\ExtensionInstaller->install() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Installer.php:569
 Composer\Installer->doInstall() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at phar:///var/www/vhosts/localhost/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///var/www/vhosts/localhost/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/vhosts/localhost/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar:///var/www/vhosts/localhost/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///var/www/vhosts/localhost/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///var/www/vhosts/localhost/composer.phar/bin/composer:43
 require() at /var/www/vhosts/localhost/composer.phar:25
```

**Comment by helhum** [comment]
fixed

**Comment by ArminVieweg** [comment]
Hmmm... I'm still able to reproduce this issue:

![image](https://user-images.githubusercontent.com/1275298/27688228-28c88f96-5cda-11e7-9088-056686159196.png)
