### ISSUE TITLE
Replacing extension name doesn't work

### ISSUE THREAD

**Issue by aimeos** [TYPO3/CmsComposerInstallers#51]
We've added a composer.json to our Aimeos TYPO3 extension (https://github.com/aimeos/aimeos-typo3/blob/master/composer.json) and added a replace section to rename the extension from `aimeos-typo3` to `aimeos`:
```
	"replace": {
		"aimeos": "self.version"
	},
```
Unfortunately, this doesn't work when executing a `composer update`. The extension is always stored in `typo3conf/ext/aimeos-typo3/` instead of `typo3conf/ext/aimeos/`. What did we do wrong?

The used root composer.json is:
```
{
    "repositories": [
        { "type": "composer", "url": "https://composer.typo3.org/" }
    ],
    "name": "vendor/example",
    "description" : "foo",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "typo3/cms": "7.6.9",
        "aimeos/aimeos-typo3": "dev-master"
    },
    "extra": {
        "typo3/cms": {
            "cms-package-dir": "{$vendor-dir}/typo3/cms",
            "web-dir": "htdocs"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Aimeos\\Aimeos\\Custom\\Composer::install"
        ],
        "post-update-cmd": [
            "Aimeos\\Aimeos\\Custom\\Composer::install"
        ]
    }
}
```

**Comment by helhum** [comment]
unfortunately typo3/cms-composer-installers conflict with composer/installers (any version other than 1.0.24) but the conflict was wrongly specified. The latter has been fixed. Please add `"composer/installers": "1.0.24"` to your root composer.json to fix your issue, until a new TYPO3 version is released, which will require a typo3/cms-composer-installers version which has a correct conflict specified
