### ISSUE TITLE
Integration with Extensionmanager when requiring extension ?

### ISSUE THREAD

**Issue by PowerKiKi** [TYPO3/CmsComposerInstallers#53]
AFAIK there is no integration between this project and `TYPO3\CMS\Extensionmanager`. Meaning that after a `composer require typo3-ter/myextension`, the extension remains inactive. And we have to go through TYPO3 backend to activate it (triggering database update if any).

Have you considered the possibility to automatically activate a `require`ed extension ? That may not be trivial (eg: if database is inaccessible yet), but that could simplify the workflow a lot.

Also an extension that would be `composer update`ed should also go through `TYPO3\CMS\Extensionmanager` to ensure that all signal/slots are dispatched as if it was updated from backend. This is actually the main reason why I see this feature as interesting. It would allow to update extension and let the extension itself update its data (via signals) whenever needed. That would completely automate the extension life-cycle. Removing the pain of going through the backend after each extension update.

Have you ever considered this ? Would it be possible in the foreseeable future ?

**Comment by helhum** [comment]
You can automate everything related to extension activation and setup with https://github.com/helhum/typo3_console right now already

**Comment by PowerKiKi** [comment]
Thanks for your reply. Unfortunately `typo3_console` must be installed
separately, so it doesn't quite fulfill my need. But I understand the need
to keep each projects focus on their own goals. Fair enough.

**Comment by helhum** [comment]
> Unfortunately `typo3_console` must be installed separately, so it doesn't quite fulfill my need

It fulfills your need now. Other than that you have to wait months (if not years) for integration in the core.

Besides that, the core also ships `typo3/cli_dispatch.phpsh extbase extension:install <extkey>`, which you can use if you do not want the convenience of typo3_console
