### ISSUE TITLE
Fatal error: Class 'Composer\Installer\BinaryInstaller' not found

### ISSUE THREAD

**Issue by regniets** [TYPO3/CmsComposerInstallers#56]
Since 1.3.1 this fatal error is being thrown in all 7.x instances:
Fatal error: Class 'Composer\Installer\BinaryInstaller' not found in vendor/typo3/cms-composer-installers/src/Installer/Plugin.php

**Comment by helhum** [comment]
> Fatal error: Class 'Composer\Installer\BinaryInstaller' not found

Please update your composer installation to composer > 1.2.0 (e.g. by running run `composer self-update`)

**Comment by regniets** [comment]
Thanks
