### ISSUE TITLE
Re-write extension to typo3conf/ext on composer update

### ISSUE THREAD

**Issue by cedricziel** [TYPO3/CmsComposerInstallers#62]
I'm experiencing an issue where a flaky internet connection leads to a half-installed state.

1. `composer update`
2. package metadata is known, package directory is created in `typo3conf/ext`
3. package download breaks. -> empty extension directoy is present in `typo3conf/ext`
4. run `composer update` again, extension directory is still empty -> broken dependency state in the cms extension matrix (composer thinks all nice and dandy)

So in conclusion this makes me think whether we should discard all local modifications in packages like composer itself does a check for changed files and asks to keep or remove them. It would lead to more stable transactions.

Any thoughts on this? I know, reproducing the issue is rather complex, but it happens for example when you access a password protected resource as package source (f.e. git.t3o) and kill the process when it asks for the password.

**Comment by helhum** [comment]
Might be. I have no plans to implement something like that.

But if you have an idea how to do this, feel free to create a pull request and I'm happy to review it.

**Comment by helhum** [comment]
I'll close this for now. If you find out what can be changed, feel free to post it here or create a pull request
