### ISSUE TITLE
Don't use _md5_values_when_last_written to check for file changes

### ISSUE THREAD

**Issue by utrotzek** [TYPO3/CmsComposerInstallers#66]
Since this option is not supported by TYPO3 anymore, the T3xDownloader should not use this to determine local changes. (related core issue: https://forge.typo3.org/issues/48040)

In my case this leads to an exception because the value isn't set correctly for several extensions.

**Comment by helhum** [comment]
> In my case this leads to an exception because the value isn't set correctly for several extensions.

Can you point out your case in more detail please? I never had issues with that.
md5 values are only read when the t3x downloader is used and this downloader actually writes these values to the ext_emconf.php after extraction.

So what are the steps to reproduce the exceptions you are seeing? Can you provide a stripped down composer.json?

**Comment by utrotzek** [comment]
> md5 values are only read when the t3x downloader is used and this downloader actually writes these values to the ext_emconf.php after extraction.

Thanks for the information! This made it clearer to me and after some debugging I figured out that this is an edge case on my end. Unfortunately this is hard to explain so I think this issue can be closed without getting into more detail.
