### ISSUE TITLE
PHP Parse Error

### ISSUE THREAD

**Issue by matzeqwertz** [TYPO3/CmsComposerInstallers#68]
I have the following problem: 
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in cms-composer-installers/src/Plugin/Util/ExtensionKeyResolver.php on line 32

If i remove the ": String" of the function "public static function resolve(PackageInterface $package): string"

in cms-composer-installers/src/Plugin/Util/ExtensionKeyResolver.php then it seems to work

**Comment by thommyhh** [comment]
This looks like the PHP incompatibility I ran into. Which version of cms-composer-installers and which php version are you using? Which composer command did you call?

**Comment by helhum** [comment]
Version 1.4.x has a dependency to PHP 7.0

See https://forge.typo3.org/issues/82025
or
https://github.com/TYPO3/CmsComposerInstallers/issues/67#issuecomment-319345285

for ideas how to handle that and prevent running into it in the future.

**Comment by matzeqwertz** [comment]
I'm using php v 5.6.29. Well that's my fault. 

thanks for the response
