### ISSUE TITLE
Consider using junctions on windows

### ISSUE THREAD

**Issue by bnf** [TYPO3/CmsComposerInstallers#69]
Is there a known good reason why typo3/cms-composer-installers tries to generate symlinks on windows (which require SeCreateSymbolicLinkPrivilege, causing the installer to suggest running composer as admin) instead of junctions (for {web-dir}/typo3) or hardlinks (for {web-dir}/index.php)?
https://github.com/TYPO3/CmsComposerInstallers/blob/33cd7b5441744da327e482c48f987e1005da1b9d/src/Plugin/Util/Filesystem.php#L92

Actually composer already creates junctions for path repositories, so it would probably be good to do the same in `typo3/cms-composer-installers`:
https://github.com/composer/composer/blob/6f3310c762b658bca64e060262ea2b1d4a1ec4b0/src/Composer/Downloader/PathDownloader.php#L94

Advantage: Junction do work without administrator privileges, which allows to drop unpleasant "please ensure your are running the Composer command with administrator rights" advise.

**Comment by helhum** [comment]
> Is there a known good reason why typo3/cms-composer-installers tries to generate symlinks on windows

Nope

> Actually composer already creates junctions for path repositories, so it would probably be good to do the same in typo3/cms-composer-installers

Sounds good.

PR is very welcome :)

**Comment by gilbertsoft** [comment]
@helhum ping

**Comment by helhum** [comment]
related or was closed thus this can be closed as well
