### ISSUE TITLE
Version 1.4 breaks semantic versioning

### ISSUE THREAD

**Issue by JostBaron** [TYPO3/CmsComposerInstallers#70]
From version 1.4.0 onwards, the package requires PHP `>=7.0.0 < 7.2`, but package version up to 1.3 did not have any requirement for the PHP version.

Is it possible to fix this by rebranding/republishing the package version from 1.4.0 upwars as 2.0.x?

This is a problem since TPYO3 7.6 requires typo3/cms-composer-installers ^1.2.8, and is still compatible with PHP 5.

**Comment by kabarakh** [comment]
👍

**Comment by helhum** [comment]
@kabarakh @JostBaron

Raising PHP version for a package is not a breaking change, as composer can handle it, in case you use it properly.

For further info see:
https://forge.typo3.org/issues/82025#note-2
https://github.com/TYPO3/CmsComposerInstallers/issues/67#issuecomment-319345285
http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html
http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api
https://getcomposer.org/doc/06-config.md#platform

**Comment by kabarakh** [comment]
As long as TYPO3 includes version "^1.2.8" and I have to manually change my composer file to include "~1.3.1" because TYPO3 7.6 won't install anymore on the php version documented on https://typo3.org/download/, then yes - it's breaking

**Comment by helhum** [comment]
> As long as TYPO3 includes version "^1.2.8" and I have to manually change my composer file to include "~1.3.1"

Please specify the PHP version you are using and the composer command you use to update `typo3/cms` with this PHP version.

**Comment by helhum** [comment]
Just for the records (discussed privatly): @kabarakh did a `composer update` on a local dev machine with PHP 7 and deployment  (on system with PHP 5) failed (because composer installers was locked to 1.4)

Solution would have been aforementioned: https://getcomposer.org/doc/06-config.md#platform
