### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to...

### ISSUE THREAD

**Issue by mkempe** [TYPO3/CmsComposerInstallers#72]
Hey there,

with version `1.4.3` i get the following PHP errors:

`
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TYPO3\CMS\Composer\Plugin\PluginImplementation::__construct() must be an instance of Composer\Script\Event, instance of Composer\Installer\PackageEvent given, called in <PROJECT_PATH>/vendor/typo3/cms-composer-installers/src/Installer/Plugin.php on line 152 and defined in <PROJECT_PATH>/vendor/typo3/cms-composer-installers/src/Plugin/PluginImplementation.php:57
...
`

Does anyone have the same errors?

I use Composer in the version `1.5.2`.

PS: I shorted the paths with `<PROJECT_PATH>`

**Comment by helhum** [comment]
oops, sorry. It contained a commit, which was not meant to be released

Reverted this with 1.4.4

**Comment by mkempe** [comment]
@helhum No problem! Thanks for the changes, errors are gone with version `1.4.4`.

Thanks again and good night!
