### ISSUE TITLE
directories by environment-variables?

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3/CmsComposerInstallers#79]
Seeing the file [CmsComposerInstallers/res/php/autoload-include.tmpl.php](https://github.com/TYPO3/CmsComposerInstallers/blob/master/res/php/autoload-include.tmpl.php) I thought it would be possible to set the paths as environment variables and those would be taken then, but I never succeeded.
Did I misunderstand the sense of that code?

**Comment by helhum** [comment]
> I thought it would be possible to set the paths as environment variables

That is true.

> Did I misunderstand the sense of that code?

No.

> but I never succeeded

It would be helpful to know what exactly you tried in order to be able to help.

**Comment by helhum** [comment]
> I thought it would be possible to set the paths as environment variables

Although I wouldn't recommend actually doing so. It shouldn't be necessary and it is likely this option is removed in future versions of the installer.

**Comment by DavidBruchmann** [comment]
Thank's for the fast answer.
I tried it in windows with git-bash as well as with cmd, so perhaps I've to try it in Linux ...,

**Comment by DavidBruchmann** [comment]
reason is that directories can change and even on one server you've to install first in a dev-directory and afterwards in a live-directory whereas the latter one can't be changed on some servers.

**Comment by DavidBruchmann** [comment]
Ok, thanks.
There exists another composer-extension for those things but I thought this would be smarter.
