### ISSUE TITLE
confused - subtree - symlinks yes/no - sitepackage

### ISSUE THREAD

**Issue by Uhradone** [TYPO3/CmsComposerInstallers#82]
I am confused and see the need for some clear best practice:

starting point are these links:
https://usetypo3.com/typo3-and-composer.html
https://usetypo3.com/typo3-subtree-split-and-composer.html
https://github.com/TYPO3/CmsComposerInstallers/issues/75

But what is best pracitce?

a. do I start with a simple composer.json
```
{
    "require": {
        "typo3/minimal": "^9.5",

       **add more core stuff - but what ??? needs some real digging**

        "heise/shariff": "^8.0",
        "gringer/news": "^99.0"

        **add all my extensions I need**


    }
}
```
b. load up manually into typo3conf/ext/ my sitepackage with a composer.json that holds the autoload information but how is this then ever reaching composer if I upload it manually?
Does autoload have to go into my start composer.json?

 ```
"autoload": {
        "psr-4": {
            "Zazuberlin\\Zazupackage\\": "Classes/"
        }
    }
```
The discussion stucki - helhum
https://github.com/TYPO3/CmsComposerInstallers/issues/75

now what? symlinks yes or no - just have all in public?

So do I understand it right, that I travel from one installation to the next with my basic TYPO3 composer.json and my manually to add sitepackage?

I think this needs some clear words since most of the information what is out there is outdated.

TH

**Comment by ervaude** [comment]
Hello @Uhradone 

There are many ways how you can do things. Also, blog posts and documentation can always be improved. However, your questions do not concern the code of this repository and therefore I think this is not the right place for them.

Please join the typo3-cms-composer channel on the TYPO3 slack or consider asking on StackOverflow.

**Comment by helhum** [comment]
I agree that documentation can be improved. A starting point could be https://docs.typo3.org/typo3cms/InstallationGuide/MigrateToComposer/Requirements.html or https://composer.typo3.org

You're also free to reach out on Slack or StackOverflow as Daniel suggests.
