### ISSUE TITLE
CmsComposerInstallers installation fails

### ISSUE THREAD

**Issue by aceArt-GmbH** [TYPO3/CmsComposerInstallers#88]
Hi,
I'm trying to install Typo3 via composer and using this [composer.json](https://github.com/TYPO3/CmsComposerInstallers/files/3926685/composer.txt) (it is a txt file because github doesn't allow to upload json files)
The problem arises with installing typo3/cms-composer-installers v1.5.0 giving following output:

`  - Installing typo3/cms-composer-installers (v1.5.0): Downloading https://api.github.com/repos/TYPO3/CmsComposerInstallers/zipball/38306da58d6b8d770b1a1308c529913b3821c0f5
Downloading (connecting...)
Following redirect (2) https://codeload.github.com/TYPO3/CmsComposerInstallers/legacy.zip/38306da58d6b8d770b1a1308c529913b3821c0f5
Downloading https://codeload.github.com/TYPO3/CmsComposerInstallers/legacy.zip/38306da58d6b8d770b1a1308c529913b3821c0f5
Downloading (100%)Writing /root/.composer/cache/files/typo3/cms-composer-installers/ce55b1d9b3043a78543aa1c7940c4fcdfbdf67b5.zip into cache from /var/www/html/vendor/typo3/cms-composer-installers/cd973b4e0f2e10474cf033048a8551be

 Extracting archiveExecuting command (CWD): unzip -qq  '/var/www/html/vendor/typo3/cms-composer-installers/cd973b4e0f2e10474cf033048a8551be' -d '/var/www/html/vendor/composer/ca053087'
Plugin installation failed, rolling back
  - Removing typo3/cms-composer-installers (v1.5.0)

  [RuntimeException]
  Could not delete /var/www/html/vendor/typo3/cms-composer-installers/res/php:`

If you need the whole console output: [consoleOutput.txt](https://github.com/TYPO3/CmsComposerInstallers/files/3926757/consoleOutput.txt)
The whole composer.lock [composer_lock.txt](https://github.com/TYPO3/CmsComposerInstallers/files/3926816/composer_lock.txt)
Hopefully I provided enough information and thank you for any help.

**Comment by helhum** [comment]
Hey. Thanks for reaching out.

Make sure the user executing the command does have enough file write permissions.

> Writing /root/.composer/cache/files/typo3/cms-composer-installers/ce55b1d9b3043a78543aa1c7940c4fcdfbdf67b5.zip

Seems like you used the root user at some point, but now don't? Anyway what you are seeing is having trouble using Composer and is unrelated with this package here.

I'm closing this ticket here, but you can reach out for help and support on [Stackoverflow](https://stackoverflow.com/questions/tagged/typo3) or [Slack](https://my.typo3.org/about-mytypo3org/slack)

**Comment by aceArt-GmbH** [comment]
Thanks for your help I was still root user, but I'll ask at stackoverflow : )
