### ISSUE TITLE
Consolidate `extra` section documentation

### ISSUE THREAD

**Issue by pixelbrackets** [TYPO3/CmsComposerInstallers#91]
Hey Hey,

the installer may read some settings from the `extra` section  of given composer files. These options are documented in the [README](https://github.com/TYPO3/CmsComposerInstallers#typo3-cms-composer-installers) of the Plugin and in the [TYPO3 Extension Architecture Docs](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html).

The setting `['extra']['typo3/cms']['web-dir']` is described in the README only. The setting `['extra']['typo3/cms']['extension-key']` is described in the API docs only. The setting `['extra']['installer-name']` is not documented at all.

I propose to consolidate this information. Either describe all available settings in the docs of this plugin or within the core docs. Add a link to each other on both places anyway.

**Comment by pixelbrackets** [comment]
I would love to send a PR. Please give me some feedback which place should be the target of the PR.

**Comment by pixelbrackets** [comment]
Btw. There used to be https://composer.typo3.org/ with some Composer docs, but this page now redirects to https://get.typo3.org/misc/composer/repository 🤔

**Comment by helhum** [comment]
Imho all that should be handled in some kind of documentation first. Then we could cross link from the readme here to the (different) documentation sources

**Comment by helhum** [comment]
> Btw. There used to be https://composer.typo3.org/ with some useful Composer docs, but this page now redirects to https://get.typo3.org/misc/composer/repository

That is the replacement for the outdated webpage. composer.typo3.org domain now only exists as long as we need this legacy composer repostitory (which is deprecated since recently)
