### ISSUE TITLE
Install Failed - Parse error: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by jackermann** [TYPO3/CmsComposerInstallers#94]
I try composer install and get the following error:

Parse error: syntax error, unexpected '?' in /var/www/host/domain.de/httpdocs/vendor/typo3/cms-composer-installers/src/Plugin/Config.php on line 198

Have somebody an idea?

**Comment by helhum** [comment]
Thanks for your question.

Seems you are using an old (<7.0) PHP version, but the package requires PHP 7.0 or higher.
